name:         sibtek-website-backend
license:      AGPL-3
license-file: LICENSE
homepage:     https://github.com/unclechu/sibtek-site#readme
author:       Viacheslav Lotsmanov
maintainer:   <lotsmanov89@gmail.com>
category:     Web

dependencies:
  - aeson
  - base
  - base-unicode-symbols
  - base64-bytestring
  - bytestring
  - containers-unicode-symbols
  - cryptohash-sha256
  - either
  - haskell-src-meta
  - postgresql-simple
  - qm-interpolated-string
  - servant
  - servant-server
  - template-haskell
  - text
  - wai
  - warp

default-extensions:
  - DataKinds
  - DeriveGeneric
  - DuplicateRecordFields
  - ExplicitNamespaces
  - FlexibleContexts
  - GADTs
  - KindSignatures
  - LambdaCase
  - NamedFieldPuns
  - OverloadedStrings
  - PolyKinds
  - QuasiQuotes
  - ScopedTypeVariables
  - TypeFamilies
  - TypeOperators
  - UnicodeSyntax
  - ViewPatterns

ghc-options:
  - -Wall
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

executables:
  sibtek-backend-exe:
    source-dirs: src
    main:        Main.hs
