name:         sibtek-db
license:      AGPL-3
license-file: LICENSE
homepage:     https://github.com/unclechu/sibtek-site#readme
author:       Viacheslav Lotsmanov
maintainer:   <lotsmanov89@gmail.com>
category:     Web

dependencies:
  - base
  - sibtek-models
  - sibtek-sugar

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveGeneric
  - DuplicateRecordFields
  - ExplicitNamespaces
  - FlexibleContexts
  - GADTs
  - KindSignatures
  - LambdaCase
  - NamedFieldPuns
  - OverloadedStrings
  - PolyKinds
  - QuasiQuotes
  - RecordWildCards
  - ScopedTypeVariables
  - TypeFamilies
  - TypeOperators
  - UnicodeSyntax
  - ViewPatterns
  - MultiParamTypeClasses
  - RankNTypes

ghc-options:
  - -Wall

library:
  source-dirs: src
