name:         sibtek-models
license:      AGPL-3
license-file: LICENSE
homepage:     https://github.com/unclechu/sibtek-site#readme
author:       Viacheslav Lotsmanov
maintainer:   <lotsmanov89@gmail.com>
category:     Web

dependencies:
  - aeson
  - base
  - containers
  - either
  - haskell-src-meta
  - qm-interpolated-string
  - servant
  - servant-server
  - sibtek-sugar
  - template-haskell
  - text

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveGeneric
  - DuplicateRecordFields
  - ExplicitNamespaces
  - FlexibleContexts
  - GADTs
  - KindSignatures
  - LambdaCase
  - NamedFieldPuns
  - OverloadedStrings
  - PolyKinds
  - QuasiQuotes
  - RecordWildCards
  - ScopedTypeVariables
  - TypeFamilies
  - TypeOperators
  - UnicodeSyntax
  - ViewPatterns

ghc-options:
  - -Wall

library:
  source-dirs: src
