name:         sibtek-db-sqlite
license:      AGPL-3
license-file: LICENSE
homepage:     https://github.com/unclechu/sibtek-site#readme
author:       Viacheslav Lotsmanov
maintainer:   <lotsmanov89@gmail.com>
category:     Web

dependencies:
  - base
  - containers
  - sibtek-db
  - sibtek-models
  - sibtek-sugar
  - sqlite-simple
  - text

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveGeneric
  - DuplicateRecordFields
  - ExplicitNamespaces
  - FlexibleContexts
  - GADTs
  - KindSignatures
  - LambdaCase
  - NamedFieldPuns
  - OverloadedStrings
  - PolyKinds
  - QuasiQuotes
  - RecordWildCards
  - ScopedTypeVariables
  - TypeFamilies
  - TypeOperators
  - UnicodeSyntax
  - ViewPatterns
  - MultiParamTypeClasses

ghc-options:
  - -Wall

library:
  source-dirs: src

executables:
  sibtek-init-db:
    source-dirs: init-db
    main:        Main.hs
    dependencies:
      - sibtek-db-sqlite
