#! /bin/sh
### BEGIN INIT INFO
# Provides:          sibtek-site
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: SIBTEK.PRO site
# Description:       SIBTEK.PRO site server deamon
### END INIT INFO

# Author: Viacheslav Lotsmanov <lotsmanov89@gmail.com>

PATH=/usr/local/bin:$PATH

. /lib/lsb/init-functions

NAME=sibtek-site
SCRIPT_NAME=/etc/init.d/$NAME
APP_PATH=/var/www/sibtek/$NAME
APP_FILE=run-production-restarter.sh
DAEMON=$APP_PATH/$APP_FILE
CONFIG_PATH=$APP_PATH/config.json
UID=sibtek
LOG_DIR=/var/log/services/$NAME
STDOUT_FILE=$LOG_DIR/stdout.log
STDERR_FILE=$LOG_DIR/stderr.log
PIDFILE=/var/run/$NAME.pid

[ -d "$APP_PATH" ] || { echo 'Application directory is not exists' 1>&2; exit 1; }

mkdir --parent "$LOG_DIR"

[ -d "$LOG_DIR" ] || { echo 'Logs directory is not exists' 1>&2; exit 1; }

do_status () {
	status_of_proc -p "$PIDFILE" "$DAEMON" "$NAME"
	return $?
}

do_start () {
	
	local retval=
	local retstatus=
	
	retval=`do_status 2>&1`
	retstatus=$?
	if [ $retstatus -eq 0 ]; then
		echo 'Application is already started' 1>&2
		return 1
	fi
	
	env \
		CONFIG_PATH="$CONFIG_PATH" \
		su "$UID" \
		"$DAEMON" \
		1>"$STDOUT_FILE" \
		2>"$STDERR_FILE" \
		&
	echo -n $! > "$PIDFILE"
	
	sleep 2
	retval=`do_status 2>&1`
	retstatus=$?
	if [ $retstatus -ne 0 ]; then
		echo "$retval" 1>&2
	else
		echo '[OK]'
	fi
	return $retstatus
}

# $1 parent pid
# $2 it's main call of function
get_all_pid_group () {
	
	local list=
	local retstatus=
	
	local count=
	local pid=
	
	if [ "$2" -eq 1 ]; then
		echo "$1" # add current pid to list
	fi
	
	list=`pgrep -P "$1"`
	retstatus=$?
	
	if [ "$2" -eq 1 ] && [ $retstatus -ne 0 ]; then
		return 0 # no child process, complete
	fi
	
	# get children pids recursive
	if [ $retstatus -eq 0 ]; then
		count=`echo "$list" | wc -l`
		for i in `seq $count`; do
			pid=`echo "$list" | head -n $i | tail -n 1`
			echo "$pid"
			get_all_pid_group "$pid" 0
		done
	fi
	
	return 0 # complete
}

# $1 pid that must die
be_sure_is_dead () {
	
	local count=
	
	count=0
	
	while kill -0 "$1" 2>/dev/null; do
		
		case "$count" in
			
			0)
				echo "Sending SIGTERM to process '$1'..."
				kill -TERM "$1"
				count=1
				;;
			1)
				echo "Process '$1' still alive, sending SIGTERM again..."
				kill -TERM "$1"
				count=2
				;;
			2)
				echo "Process '$1' still alive, sending SIGKILL..."
				kill -KILL "$1"
				count=3
				;;
			*)
				echo "[ERROR] Cannot kill the process '$1'."
				return 1
				;;
		esac
		
		sleep 1
	done
	
	echo "[OK] Process '$1' is dead."
	return 0
}

# $1 pids that must die list
deep_kill () {
	
	local count=
	local pid=
	
	count=`echo "$1" | wc -l`
	for i in `seq $count`; do
		pid=`echo "$1" | head -n $i | tail -n 1`
		be_sure_is_dead "$pid" || return 1
	done
	
	return 0
}

do_stop () {
	
	local retstatus=
	local pid=
	local pids_list=
	
	do_status 1>/dev/null
	retstatus=$?
	
	if [ $retstatus -eq 0 ]; then
		
		pid=`cat "$PIDFILE" 2>/dev/null`
		retstatus=$?
		
		if [ $retstatus -ne 0 ] || [ -z "$pid" ]; then
			echo "Cannot read pid from pidfile '$PIDFILE'" 1>&2
			return $retstatus
		fi
		
		pid=`echo "$pid" | head -n1 | xargs | tr -dc '0-9' 2>/dev/null`
		retstatus=$?
		
		if [ $retstatus -ne 0 ] || [ -z "$pid" ]; then
			echo "Cannot parse pid number from pidfile '$PIDFILE'" 1>&2
			return $retstatus
		fi
		
		pids_list=`get_all_pid_group "$pid" 1`
		retstatus=$?
		[ $retstatus -ne 0 ] && return $retstatus
		
		deep_kill "$pids_list"
		retstatus=$?
		[ $retstatus -ne 0 ] && return $retstatus
		
		echo '[OK]'
		return 0
	fi
	
	return $retstatus
}

case "$1" in
	
	start)
		do_start
		exit $?
		;;
		
	stop)
		do_stop
		exit $?
		;;
		
	restart)
		
		if do_status 2>&1 1>/dev/null; then
			echo 'Stopping daemon...'
			do_stop || exit $?
			sleep 2
		fi
		
		echo 'Starting daemon...'
		do_start
		exit $?
		;;
		
	status)
		do_status
		exit $?
		;;
		
	*)
		echo "Usage: $SCRIPTNAME {start|stop|restart|status}" 1>&2
		exit 3
		;;
esac

:
